# config/services.yaml
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # explicitly register controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # specific controller service
    App\Controller\EmailVerificationController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']
    App\Service\VideoService:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'